package com.example.navyuga.feature.roi.presentation

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

class RoiPdfGenerator(private val context: Context) {

    // A4 Dimensions (PostScript points)
    private val PAGE_WIDTH = 595
    private val PAGE_HEIGHT = 842
    private val MARGIN = 50f
    private val BOTTOM_LIMIT = PAGE_HEIGHT - MARGIN

    fun generateAndSharePdf(state: RoiState) {
        val pdfDocument = PdfDocument()
        val paint = Paint()

        // --- PAGINATION STATE ---
        var pageNumber = 1
        // We initialize these, but they will be managed by our helper functions
        var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas
        var y = 0f

        // --- HELPER FUNCTIONS (Local to this scope to access canvas/page) ---

        fun drawHeader() {
            paint.color = Color.parseColor("#2979FF") // Brand Blue
            paint.style = Paint.Style.FILL
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 100f, paint)

            paint.color = Color.WHITE
            paint.textSize = 24f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("Investment Analysis Report", MARGIN, 60f, paint)

            paint.textSize = 14f
            paint.typeface = Typeface.DEFAULT
            val subText = if (pageNumber > 1) "Generated by Nav Yuga (Page $pageNumber)" else "Generated by Nav Yuga"
            canvas.drawText(subText, MARGIN, 85f, paint)

            // Reset Y for content start
            y = 140f
        }

        fun startNewPage() {
            pdfDocument.finishPage(page)
            pageNumber++
            pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            page = pdfDocument.startPage(pageInfo)
            canvas = page.canvas // Update the canvas reference!
            drawHeader() // Draw header on the new page
        }

        fun checkSpace(heightNeeded: Float) {
            if (y + heightNeeded > BOTTOM_LIMIT) {
                startNewPage()
            }
        }

        // --- DRAW ROW HELPER ---
        fun drawRow(label: String, value: String) {
            checkSpace(25f) // Ensure space for this row

            val rightEdge = PAGE_WIDTH - MARGIN

            paint.color = Color.DKGRAY
            paint.textSize = 12f
            paint.typeface = Typeface.DEFAULT
            canvas.drawText(label, MARGIN, y, paint)

            paint.color = Color.BLACK
            paint.textAlign = Paint.Align.RIGHT
            canvas.drawText(value, rightEdge, y, paint)

            paint.textAlign = Paint.Align.LEFT // Reset
            y += 20f
        }

        fun drawSectionTitle(title: String) {
            checkSpace(40f) // Title needs more space

            paint.color = Color.parseColor("#1565C0") // Darker Blue
            paint.textSize = 16f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText(title, MARGIN, y, paint)

            // Underline
            val rightEdge = PAGE_WIDTH - MARGIN
            paint.strokeWidth = 2f
            canvas.drawLine(MARGIN, y + 8f, rightEdge, y + 8f, paint)
            paint.strokeWidth = 0f // Reset

            y += 30f // Add spacing after title
        }

        fun formatCurrency(amount: String?): String {
            val value = amount?.toDoubleOrNull() ?: 0.0
            if (value == 0.0) return "-"
            return "₹ ${String.format("%,.0f", value)}"
        }

        // ============================
        // START DRAWING CONTENT
        // ============================

        drawHeader() // Draw initial header

        // 1. EXECUTIVE SUMMARY
        checkSpace(120f) // Big box needs space
        drawSectionTitle("Executive Summary")

        val rightEdge = PAGE_WIDTH - MARGIN
        val roiPaint = Paint()
        roiPaint.color = Color.parseColor("#E8F5E9") // Light Green
        roiPaint.style = Paint.Style.FILL
        canvas.drawRect(MARGIN, y, rightEdge, y + 60f, roiPaint)

        paint.color = Color.parseColor("#2E7D32") // Dark Text
        paint.textSize = 30f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText(String.format("%.2f%% ROI", state.calculatedRoi), rightEdge - 20f, y + 40f, paint)

        paint.textAlign = Paint.Align.LEFT
        paint.textSize = 14f
        canvas.drawText("Projected Annual Yield", MARGIN + 20f, y + 35f, paint)

        y += 90f

        // 2. PROPERTY INFO
        drawSectionTitle("1. Property Information")
        drawRow("Property Name", state.propertyName.ifBlank { "-" })
        drawRow("Address", state.propertyAddress.ifBlank { "-" })
        drawRow("Type", state.propertyType)
        drawRow("Building Age", if (state.buildingAge.isNotBlank()) "${state.buildingAge} Years" else "-")
        drawRow("Saleable Area", if (state.saleableArea.isNotBlank()) "${state.saleableArea} Sq Ft" else "-")
        drawRow("Floor", state.floor.ifBlank { "-" })
        drawRow("Car Park", state.carPark.ifBlank { "-" })
        y += 15f

        // 3. LEASE INFO
        drawSectionTitle("2. Lease Information")
        drawRow("Tenant Name", state.tenantName.ifBlank { "-" })
        drawRow("Period of Occupation", if (state.periodOfOccupation.isNotBlank()) "${state.periodOfOccupation} Years" else "-")
        drawRow("Lock-in Period", if (state.lockInPeriod.isNotBlank()) "${state.lockInPeriod} Years" else "-")

        val escText = if (state.escalationPercent.isNotBlank() && state.escalationYears.isNotBlank())
            "${state.escalationPercent}% every ${state.escalationYears} Years" else "-"
        drawRow("Escalation", escText)

        y += 10f
        checkSpace(20f)
        paint.color = Color.DKGRAY
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Income Breakdown", MARGIN, y, paint)
        y += 20f

        drawRow("Monthly Rent", formatCurrency(state.monthlyRent))
        drawRow("Security Deposit", formatCurrency(state.securityDeposit))
        drawRow("Gross Annual Rent", formatCurrency(state.grossAnnualRent.toString()))
        drawRow("GST (18%)", formatCurrency(state.gstAmount.toString()) + " (Pass-through)")
        y += 15f

        // 4. EXPENSES
        drawSectionTitle("3. Expenses (Outflow)")
        drawRow("Property Tax / Year", formatCurrency(state.totalPropertyTaxAnnually.toString()))

        val maintLabel = if(state.isMaintenanceByLandlord) "Paid by Landlord" else "Paid by Tenant"
        val maintCost = if(state.isMaintenanceByLandlord) (state.maintenanceCost.toDoubleOrNull() ?: 0.0) * 12 else 0.0
        val maintText = if (maintCost > 0) "${formatCurrency(maintCost.toString())} ($maintLabel)" else "- ($maintLabel)"
        drawRow("Maintenance / Year", maintText)

        checkSpace(25f)
        paint.color = Color.BLACK
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        drawRow("NET ANNUAL INCOME", formatCurrency(state.netAnnualIncome.toString()))
        y += 15f

        // 5. INVESTMENT BREAKDOWN
        drawSectionTitle("4. Investment Breakdown")
        drawRow("Base Acquisition Cost", formatCurrency(state.acquisitionCost))
        drawRow("Registry (8%)", formatCurrency(state.registryCost.toString()))
        drawRow("Legal Charges", formatCurrency(state.legalCharges))

        val otherCosts = (state.electricityCharges.toDoubleOrNull()?:0.0) +
                (state.dgCharges.toDoubleOrNull()?:0.0) +
                (state.fireFightingCharges.toDoubleOrNull()?:0.0)
        drawRow("Other Charges", formatCurrency(otherCosts.toString()))

        checkSpace(25f)
        paint.color = Color.BLACK
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        drawRow("TOTAL INVESTMENT", formatCurrency(state.totalInvestment.toString()))

        // --- FINISH ---
        pdfDocument.finishPage(page)
        saveAndShare(pdfDocument)
    }

    private fun saveAndShare(document: PdfDocument) {
        try {
            val file = File(context.cacheDir, "ROI_Report.pdf")
            val fos = FileOutputStream(file)
            document.writeTo(fos)
            document.close()
            fos.close()

            val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(intent, "Share ROI Report")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}