package com.example.navyuga.feature.roi.presentation

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

class RoiPdfGenerator(private val context: Context) {

    private val PAGE_WIDTH = 595
    private val PAGE_HEIGHT = 842
    private val MARGIN = 50f
    private val BOTTOM_LIMIT = PAGE_HEIGHT - MARGIN

    // BRAND BLUE COLOR
    private val BRAND_BLUE = Color.parseColor("#2979FF")
    private val LIGHT_BLUE_BG = Color.parseColor("#E3F2FD")

    fun generateAndSharePdf(state: RoiState) {
        val pdfDocument = PdfDocument()
        val paint = Paint()

        var pageNumber = 1
        var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas
        var y = 0f

        // --- HELPER FUNCTIONS ---

        fun drawHeader() {
            paint.color = BRAND_BLUE
            paint.style = Paint.Style.FILL
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 100f, paint)

            paint.color = Color.WHITE
            paint.textSize = 24f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)

            // CUSTOM HEADER: "{Tenant Name} ROI Calculation"
            val title = "${state.tenantName.ifBlank { "Property" }} ROI Calculation"
            canvas.drawText(title, MARGIN, 60f, paint)

            paint.textSize = 12f
            paint.typeface = Typeface.DEFAULT
            // CUSTOM FOOTER/SUBHEADER text
            val subText = "Generated by Navyuga- India’s most trusted ROI Calculator"
            canvas.drawText(subText, MARGIN, 85f, paint)

            y = 140f
        }

        fun startNewPage() {
            pdfDocument.finishPage(page)
            pageNumber++
            pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            page = pdfDocument.startPage(pageInfo)
            canvas = page.canvas
            drawHeader()
        }

        fun checkSpace(heightNeeded: Float) {
            if (y + heightNeeded > BOTTOM_LIMIT) {
                startNewPage()
            }
        }

        fun drawRow(label: String, value: String, isBold: Boolean = false) {
            checkSpace(25f)
            val rightEdge = PAGE_WIDTH - MARGIN

            paint.color = Color.DKGRAY
            paint.textSize = 12f
            paint.typeface = if(isBold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
            canvas.drawText(label, MARGIN, y, paint)

            paint.color = if(isBold) BRAND_BLUE else Color.BLACK
            paint.textAlign = Paint.Align.RIGHT
            canvas.drawText(value, rightEdge, y, paint)

            paint.textAlign = Paint.Align.LEFT
            y += 20f
        }

        fun drawSectionTitle(title: String) {
            checkSpace(40f)
            paint.color = BRAND_BLUE
            paint.textSize = 16f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText(title, MARGIN, y, paint)

            val rightEdge = PAGE_WIDTH - MARGIN
            paint.strokeWidth = 2f
            canvas.drawLine(MARGIN, y + 8f, rightEdge, y + 8f, paint)
            paint.strokeWidth = 0f
            y += 30f
        }

        fun formatCurrency(amount: String?): String {
            val value = amount?.toDoubleOrNull() ?: 0.0
            if (value == 0.0) return "-"
            return "₹ ${String.format("%,.0f", value)}"
        }

        // ============================
        // CONTENT GENERATION
        // ============================

        drawHeader()

        // 1. PROPERTY INFO
        drawSectionTitle("1. Property Information")
        drawRow("Property Name", state.propertyName.ifBlank { "-" })
        drawRow("Address", state.propertyAddress.ifBlank { "-" })
        drawRow("Type", state.propertyType)
        drawRow("Age", if (state.buildingAge.isNotBlank()) "${state.buildingAge} Years" else "-")
        drawRow("Area", if (state.saleableArea.isNotBlank()) "${state.saleableArea} Sq Ft" else "-")
        drawRow("Floor", state.floor.ifBlank { "-" })
        drawRow("Car Park", state.carPark.ifBlank { "-" })
        y += 15f

        // 2. LEASE INFO
        drawSectionTitle("2. Lease Information")
        drawRow("Tenant Name", state.tenantName.ifBlank { "-" })
        drawRow("Period of Occupation", if (state.periodOfOccupation.isNotBlank()) "${state.periodOfOccupation} Years" else "-")

        val escText = if (state.escalationPercent.isNotBlank() && state.escalationYears.isNotBlank())
            "${state.escalationPercent}% every ${state.escalationYears} Years" else "-"
        drawRow("Escalation", escText)
        y += 10f

        // 3. INCOME & EXPENSES
        drawSectionTitle("3. Financial Analysis")
        drawRow("Monthly Rent", formatCurrency(state.monthlyRent))
        drawRow("Gross Annual Rent", formatCurrency(state.grossAnnualRent.toString()))
        drawRow("Annual Property Tax", formatCurrency(state.totalPropertyTaxAnnually.toString()))

        val maintCost = if(state.isMaintenanceByLandlord) (state.maintenanceCost.toDoubleOrNull() ?: 0.0) * 12 else 0.0
        if (maintCost > 0) drawRow("Annual Maintenance (Landlord)", formatCurrency(maintCost.toString()))

        drawRow("GST (18% Pass-through)", formatCurrency(state.gstAmount.toString()))

        // Net Annual Income
        y += 10f
        checkSpace(30f)
        paint.color = BRAND_BLUE
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 14f
        canvas.drawText("NET ANNUAL INCOME", MARGIN, y, paint)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText(formatCurrency(state.netAnnualIncome.toString()), PAGE_WIDTH - MARGIN, y, paint)
        paint.textAlign = Paint.Align.LEFT
        y += 25f

        // 4. PRICE BREAKDOWN
        drawSectionTitle("4. Price Breakdown")
        if (state.isBuyerMode) {
            drawRow("Base Price", formatCurrency(state.acquisitionCost))
        } else {
            drawRow("SELLING PRICE", formatCurrency(state.calculatedSellingPrice.toString()), isBold = true)
        }
        drawRow("Registry (8%)", formatCurrency(state.registryCost.toString()))
        drawRow("Legal & Others", formatCurrency(state.totalOtherCharges.toString()))

        y += 5f
        paint.strokeWidth = 1f
        paint.color = Color.LTGRAY
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, paint)
        y += 20f

        // NOTE: For Seller, "Total Investment" is moved to the Blue Box.
        if (state.isBuyerMode) {
            drawRow("TOTAL INVESTMENT", formatCurrency(state.totalInvestment.toString()), isBold = true)
        }
        y += 20f

        // 5. RESULT BOX (Bottom)
        checkSpace(130f)

        val rightEdge = PAGE_WIDTH - MARGIN
        val boxPaint = Paint()
        boxPaint.color = BRAND_BLUE // BLUE BOX
        boxPaint.style = Paint.Style.FILL
        // Increase box height for Sellers to fit two lines comfortably
        val boxHeight = if(state.isBuyerMode) 80f else 110f
        canvas.drawRect(MARGIN, y, rightEdge, y + boxHeight, boxPaint)

        paint.color = Color.WHITE
        paint.textAlign = Paint.Align.CENTER

        if (state.isBuyerMode) {
            // --- BUYER BOX (Original) ---
            paint.textSize = 16f
            paint.typeface = Typeface.DEFAULT
            canvas.drawText("PROJECTED ROI", (PAGE_WIDTH / 2).toFloat(), y + 30f, paint)

            paint.textSize = 36f
            paint.typeface = Typeface.DEFAULT_BOLD
            canvas.drawText(String.format("%.2f%%", state.calculatedRoi),
                (PAGE_WIDTH / 2).toFloat(), y + 65f, paint)
        } else {
            // --- SELLER BOX (New Requirement) ---
            // Line 1: Total Investment
            paint.textSize = 14f
            paint.typeface = Typeface.DEFAULT
            canvas.drawText("TOTAL INVESTMENT", (PAGE_WIDTH / 2).toFloat(), y + 25f, paint)

            paint.textSize = 20f
            paint.typeface = Typeface.DEFAULT_BOLD
            canvas.drawText(formatCurrency(state.totalInvestment.toString()), (PAGE_WIDTH / 2).toFloat(), y + 50f, paint)

            // Line 2: Target ROI
            paint.textSize = 14f
            paint.typeface = Typeface.DEFAULT
            canvas.drawText("TARGET ROI", (PAGE_WIDTH / 2).toFloat(), y + 75f, paint)

            paint.textSize = 22f
            paint.typeface = Typeface.DEFAULT_BOLD
            canvas.drawText(String.format("%.2f%%", state.calculatedRoi),
                (PAGE_WIDTH / 2).toFloat(), y + 100f, paint)
        }

        // FINISH
        pdfDocument.finishPage(page)
        saveAndShare(pdfDocument)
    }

    private fun saveAndShare(document: PdfDocument) {
        try {
            val file = File(context.cacheDir, "ROI_Report.pdf")
            val fos = FileOutputStream(file)
            document.writeTo(fos)
            document.close()
            fos.close()

            val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(intent, "Share ROI Report")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}