package com.example.navyuga.feature.roi.presentation

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.NumberFormat
import java.util.Locale

enum class PdfMode {
    REPORT,
    COUNTER_OFFER
}

class RoiPdfGenerator(private val context: Context) {

    private val PAGE_WIDTH = 595
    private val PAGE_HEIGHT = 842
    private val MARGIN = 50f
    private val BOTTOM_LIMIT = PAGE_HEIGHT - MARGIN

    // COLORS
    private val BRAND_BLUE = Color.parseColor("#0F172A")

    suspend fun generateAndSharePdf(state: RoiState, mode: PdfMode) {
        withContext(Dispatchers.IO) {
            try {
                createPdfInternal(state, mode)
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }

    private fun createPdfInternal(state: RoiState, mode: PdfMode) {
        val pdfDocument = PdfDocument()
        val paint = Paint()

        var pageNumber = 1
        var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas
        var y = 0f

        // --- HELPER FUNCTIONS ---

        fun drawHeader() {
            paint.color = BRAND_BLUE
            paint.style = Paint.Style.FILL
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 100f, paint)

            paint.color = Color.WHITE
            paint.textSize = 24f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)

            // DYNAMIC HEADER
            val title = if (mode == PdfMode.COUNTER_OFFER) {
                "Counter Offer Proposal"
            } else {
                "${state.tenantName.ifBlank { "Property" }} ROI Calculation"
            }
            canvas.drawText(title, MARGIN, 60f, paint)

            paint.textSize = 12f
            paint.typeface = Typeface.DEFAULT
            val subText = "Generated by Navyuga - Transparent Real Estate Solutions"
            canvas.drawText(subText, MARGIN, 85f, paint)

            y = 140f
        }

        fun startNewPage() {
            pdfDocument.finishPage(page)
            pageNumber++
            pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            page = pdfDocument.startPage(pageInfo)
            canvas = page.canvas
            drawHeader()
        }

        fun checkSpace(heightNeeded: Float) {
            if (y + heightNeeded > BOTTOM_LIMIT) {
                startNewPage()
            }
        }

        fun drawRow(label: String, value: String, isBold: Boolean = false) {
            checkSpace(25f)
            val rightEdge = PAGE_WIDTH - MARGIN

            paint.color = Color.DKGRAY
            paint.textSize = 12f
            paint.typeface = if(isBold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
            canvas.drawText(label, MARGIN, y, paint)

            paint.color = if(isBold) BRAND_BLUE else Color.BLACK
            paint.textAlign = Paint.Align.RIGHT
            canvas.drawText(value, rightEdge, y, paint)

            paint.textAlign = Paint.Align.LEFT
            y += 20f
        }

        fun drawSectionTitle(title: String) {
            checkSpace(40f)
            paint.color = BRAND_BLUE
            paint.textSize = 16f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText(title, MARGIN, y, paint)

            val rightEdge = PAGE_WIDTH - MARGIN
            paint.strokeWidth = 2f
            canvas.drawLine(MARGIN, y + 8f, rightEdge, y + 8f, paint)
            paint.strokeWidth = 0f
            y += 30f
        }

        // ⚡ UPDATED: Indian Number Format
        fun formatCurrency(amount: Any?): String {
            val d = amount.toString().toDoubleOrNull() ?: 0.0
            if (d == 0.0) return "-"
            val formatter = NumberFormat.getInstance(Locale("en", "IN"))
            formatter.maximumFractionDigits = 0
            return "₹ ${formatter.format(d)}"
        }

        // ============================
        // CONTENT GENERATION
        // ============================

        drawHeader()

        // 1. PROPERTY INFO
        drawSectionTitle("1. Property Information")
        drawRow("Property Name", state.propertyName.ifBlank { "-" })
        drawRow("Address", state.propertyAddress.ifBlank { "-" })
        drawRow("Type", state.propertyType)
        drawRow("Building Age", if (state.buildingAge.isNotBlank()) "${state.buildingAge} Years" else "-")
        drawRow("Saleable Area", if (state.saleableArea.isNotBlank()) "${state.saleableArea} Sq Ft" else "-")
        drawRow("Floor Level", state.floor.ifBlank { "-" })
        drawRow("Car Park", state.carPark.ifBlank { "-" })
        y += 15f

        // 2. LEASE INFO
        drawSectionTitle("2. Lease Information")
        drawRow("Tenant Name", state.tenantName.ifBlank { "-" })
        drawRow("Period of Occupation", if (state.periodOfOccupation.isNotBlank()) "${state.periodOfOccupation} Years" else "-")

        val escText = if (state.escalationPercent.isNotBlank() && state.escalationYears.isNotBlank())
            "${state.escalationPercent}% every ${state.escalationYears} Years" else "-"
        drawRow("Escalation", escText)
        drawRow("Lock-in Period", state.lockInPeriod.ifBlank { "-" })
        y += 10f

        // 3. FINANCIAL ANALYSIS
        drawSectionTitle("3. Financial Analysis")
        drawRow("Monthly Rent", formatCurrency(state.monthlyRent))
        drawRow("Gross Annual Rent", formatCurrency(state.grossAnnualRent))
        drawRow("Annual Property Tax", formatCurrency(state.totalPropertyTaxAnnually))

        val maintCost = if(state.isMaintenanceByLandlord) (state.maintenanceCost.toDoubleOrNull() ?: 0.0) * 12 else 0.0
        if (maintCost > 0) drawRow("Annual Maintenance (Landlord)", formatCurrency(maintCost))

        drawRow("GST (18% Pass-through)", formatCurrency(state.gstAmount))

        y += 10f
        checkSpace(30f)
        paint.color = BRAND_BLUE
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 14f
        canvas.drawText("NET ANNUAL INCOME", MARGIN, y, paint)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText(formatCurrency(state.netAnnualIncome), PAGE_WIDTH - MARGIN, y, paint)
        paint.textAlign = Paint.Align.LEFT
        y += 25f

        // 4. PRICE BREAKDOWN
        drawSectionTitle("4. Investment Breakdown")
        // Logic: If Counter Offer, use Counter Price, else use standard state price
        val basePrice = if (mode == PdfMode.COUNTER_OFFER) state.counterOfferPrice ?: 0.0 else if (state.isBuyerMode) state.acquisitionCost.toDoubleOrNull() ?: 0.0 else state.calculatedSellingPrice

        val registry = basePrice * 0.08
        val otherCharges = state.totalOtherCharges
        val totalInvestment = basePrice + registry + otherCharges

        drawRow(if (mode == PdfMode.COUNTER_OFFER) "PROPOSED OFFER PRICE" else "Base Price", formatCurrency(basePrice), isBold = (mode == PdfMode.COUNTER_OFFER))
        drawRow("Registry (8%)", formatCurrency(registry))
        drawRow("Legal & Others", formatCurrency(otherCharges))

        y += 5f
        paint.strokeWidth = 1f
        paint.color = Color.LTGRAY
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, paint)
        y += 20f

        drawRow("TOTAL INVESTMENT", formatCurrency(totalInvestment), isBold = true)
        y += 20f

        // 5. RESULT BOX (Bottom)
        checkSpace(130f)

        val rightEdge = PAGE_WIDTH - MARGIN
        val boxPaint = Paint()
        boxPaint.color = BRAND_BLUE
        boxPaint.style = Paint.Style.FILL
        val boxHeight = 110f
        canvas.drawRect(MARGIN, y, rightEdge, y + boxHeight, boxPaint)

        paint.color = Color.WHITE
        paint.textAlign = Paint.Align.CENTER

        // BOX CONTENT
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT

        if (mode == PdfMode.COUNTER_OFFER) {
            canvas.drawText("PROPOSED COUNTER OFFER", (PAGE_WIDTH / 2).toFloat(), y + 30f, paint)

            paint.textSize = 28f
            paint.typeface = Typeface.DEFAULT_BOLD
            canvas.drawText(formatCurrency(basePrice), (PAGE_WIDTH / 2).toFloat(), y + 65f, paint)

            paint.textSize = 14f
            paint.typeface = Typeface.DEFAULT
            canvas.drawText("Yielding ROI: ${String.format("%.2f%%", state.counterOfferRoi ?: 0.0)}", (PAGE_WIDTH / 2).toFloat(), y + 90f, paint)
        } else {
            val label = if(state.isBuyerMode) "PROJECTED ROI" else "TARGET ROI"
            canvas.drawText(label, (PAGE_WIDTH / 2).toFloat(), y + 30f, paint)

            paint.textSize = 36f
            paint.typeface = Typeface.DEFAULT_BOLD
            canvas.drawText(String.format("%.2f%%", state.calculatedRoi),
                (PAGE_WIDTH / 2).toFloat(), y + 70f, paint)
        }

        // FINISH
        pdfDocument.finishPage(page)
        saveAndShare(pdfDocument)
    }

    private fun saveAndShare(document: PdfDocument) {
        try {
            val fileName = "Navyuga_Report_${System.currentTimeMillis()}.pdf"
            val file = File(context.cacheDir, fileName)
            val fos = FileOutputStream(file)
            document.writeTo(fos)
            document.close()
            fos.close()

            val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(intent, "Share Report")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}